# flake8: noqa: PYI021

from typing import Final, Mapping, Sized

EARTH_RADIUS_METERS: Final[float]

# Opaque handle returned by Rust geometry factories. Placeholder until full
# geometry bindings land; stored by Python wrappers to keep lifetimes stable.
GeometryHandle = Sized

CRSLike = int | str | None

GeoJSONMapping = Mapping[str, object]

def distance(a: GeometryHandle, b: GeometryHandle, *, crs: CRSLike | None = ...) -> float: ...
def equals(a: GeometryHandle, b: GeometryHandle) -> bool: ...
def intersects(a: GeometryHandle, b: GeometryHandle) -> bool: ...
def within(a: GeometryHandle, b: GeometryHandle) -> bool: ...
def buffer(geometry: GeometryHandle, distance_meters: float) -> GeometryHandle: ...
def centroid(geometry: GeometryHandle) -> GeometryHandle: ...
def loads_wkt(wkt: str, *, crs: CRSLike | None = ...) -> GeometryHandle: ...
def dumps_wkt(geometry: GeometryHandle, *, crs: CRSLike | None = ...) -> str: ...
def loads_wkb(wkb: bytes, *, crs: CRSLike | None = ...) -> GeometryHandle: ...
def dumps_wkb(geometry: GeometryHandle, *, crs: CRSLike | None = ...) -> bytes: ...
def loads_geojson(mapping: GeoJSONMapping, *, crs: CRSLike | None = ...) -> GeometryHandle: ...
def dumps_geojson(geometry: GeometryHandle, *, crs: CRSLike | None = ...) -> GeoJSONMapping: ...
